services:
  php:
    build: .
    volumes:
      - .:/var/www/project
      - ./var:/var/www/project/var
    environment:
      DATABASE_URL: "mysql://symfony:password@mysql:3306/symfony?serverVersion=5.7"
      APP_ENV: dev # Mieux en dev pour le développement
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - symfony-network

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80" # Port modifié pour éviter les conflits
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/project
    depends_on:
      - php
    networks:
      - symfony-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - symfony-network

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_USER: symfony
      PMA_PASSWORD: password
      UPLOAD_LIMIT: 128M
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - symfony-network

volumes:
  mysql_data:

networks:
  symfony-network: