version: '3.8'

services:
  php:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/project
      - ./var:/var/www/project/var
    environment:
      DATABASE_URL: "mysql://symfony:password@mysql:3306/symfony?serverVersion=5.7"
      APP_ENV: prod
    depends_on:
      - mysql
    networks:
      - symfony-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - symfony-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 128M
      environment:
      PMA_USER: symfony
      PMA_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - symfony-network

volumes:
  mysql_data:

networks:
  symfony-network: